import gen_qmediacontrol_types
export gen_qmediacontrol_types
type QCameraViewfinderSettingsControl*  = object of gen_qmediacontrol_types.QMediaControl
import gen_qmediacontrol_types
export gen_qmediacontrol_types
type QCameraViewfinderSettingsControl2*  = object of gen_qmediacontrol_types.QMediaControl

