#pragma once
#ifndef MIQT_QT_RESTRICTED_EXTRAS_QSCINTILLA_GEN_QSCISCINTILLABASE_H
#define MIQT_QT_RESTRICTED_EXTRAS_QSCINTILLA_GEN_QSCISCINTILLABASE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../../libmiqt/libmiqt.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
class QAbstractScrollArea;
class QActionEvent;
class QChildEvent;
class QCloseEvent;
class QColor;
class QContextMenuEvent;
class QDragEnterEvent;
class QDragLeaveEvent;
class QDragMoveEvent;
class QDropEvent;
class QEvent;
class QFocusEvent;
class QFrame;
class QHideEvent;
class QImage;
class QInputMethodEvent;
class QKeyEvent;
class QMetaMethod;
class QMetaObject;
class QMimeData;
class QMouseEvent;
class QMoveEvent;
class QObject;
class QPaintDevice;
class QPaintEngine;
class QPaintEvent;
class QPainter;
class QPixmap;
class QPoint;
class QRect;
class QResizeEvent;
class QScrollBar;
class QShowEvent;
class QSize;
class QTabletEvent;
class QTimerEvent;
class QUrl;
class QVariant;
class QWheelEvent;
class QWidget;
class QsciScintillaBase;
#else
typedef struct QAbstractScrollArea QAbstractScrollArea;
typedef struct QActionEvent QActionEvent;
typedef struct QChildEvent QChildEvent;
typedef struct QCloseEvent QCloseEvent;
typedef struct QColor QColor;
typedef struct QContextMenuEvent QContextMenuEvent;
typedef struct QDragEnterEvent QDragEnterEvent;
typedef struct QDragLeaveEvent QDragLeaveEvent;
typedef struct QDragMoveEvent QDragMoveEvent;
typedef struct QDropEvent QDropEvent;
typedef struct QEvent QEvent;
typedef struct QFocusEvent QFocusEvent;
typedef struct QFrame QFrame;
typedef struct QHideEvent QHideEvent;
typedef struct QImage QImage;
typedef struct QInputMethodEvent QInputMethodEvent;
typedef struct QKeyEvent QKeyEvent;
typedef struct QMetaMethod QMetaMethod;
typedef struct QMetaObject QMetaObject;
typedef struct QMimeData QMimeData;
typedef struct QMouseEvent QMouseEvent;
typedef struct QMoveEvent QMoveEvent;
typedef struct QObject QObject;
typedef struct QPaintDevice QPaintDevice;
typedef struct QPaintEngine QPaintEngine;
typedef struct QPaintEvent QPaintEvent;
typedef struct QPainter QPainter;
typedef struct QPixmap QPixmap;
typedef struct QPoint QPoint;
typedef struct QRect QRect;
typedef struct QResizeEvent QResizeEvent;
typedef struct QScrollBar QScrollBar;
typedef struct QShowEvent QShowEvent;
typedef struct QSize QSize;
typedef struct QTabletEvent QTabletEvent;
typedef struct QTimerEvent QTimerEvent;
typedef struct QUrl QUrl;
typedef struct QVariant QVariant;
typedef struct QWheelEvent QWheelEvent;
typedef struct QWidget QWidget;
typedef struct QsciScintillaBase QsciScintillaBase;
#endif

struct QsciScintillaBase_VTable {
	void (*destructor)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self);
	QMetaObject* (*metaObject)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self);
	void* (*metacast)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, const char* param1);
	int (*metacall)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, int param1, int param2, void** param3);
	bool (*canInsertFromMimeData)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self, QMimeData* source);
	struct miqt_string (*fromMimeData)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self, QMimeData* source, bool* rectangular);
	QMimeData* (*toMimeData)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self, struct miqt_string text, bool rectangular);
	void (*changeEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QEvent* e);
	void (*contextMenuEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QContextMenuEvent* e);
	void (*dragEnterEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QDragEnterEvent* e);
	void (*dragLeaveEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QDragLeaveEvent* e);
	void (*dragMoveEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QDragMoveEvent* e);
	void (*dropEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QDropEvent* e);
	void (*focusInEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QFocusEvent* e);
	void (*focusOutEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QFocusEvent* e);
	bool (*focusNextPrevChild)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, bool next);
	void (*keyPressEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QKeyEvent* e);
	void (*inputMethodEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QInputMethodEvent* event);
	QVariant* (*inputMethodQuery)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self, int query);
	void (*mouseDoubleClickEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QMouseEvent* e);
	void (*mouseMoveEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QMouseEvent* e);
	void (*mousePressEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QMouseEvent* e);
	void (*mouseReleaseEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QMouseEvent* e);
	void (*paintEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QPaintEvent* e);
	void (*resizeEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QResizeEvent* e);
	void (*scrollContentsBy)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, int dx, int dy);
	QSize* (*minimumSizeHint)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self);
	QSize* (*sizeHint)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self);
	void (*setupViewport)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QWidget* viewport);
	bool (*eventFilter)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QObject* param1, QEvent* param2);
	bool (*event)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QEvent* param1);
	bool (*viewportEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QEvent* param1);
	void (*wheelEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QWheelEvent* param1);
	QSize* (*viewportSizeHint)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self);
	int (*devType)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self);
	void (*setVisible)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, bool visible);
	int (*heightForWidth)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self, int param1);
	bool (*hasHeightForWidth)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self);
	QPaintEngine* (*paintEngine)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self);
	void (*keyReleaseEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QKeyEvent* event);
	void (*enterEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QEvent* event);
	void (*leaveEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QEvent* event);
	void (*moveEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QMoveEvent* event);
	void (*closeEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QCloseEvent* event);
	void (*tabletEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QTabletEvent* event);
	void (*actionEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QActionEvent* event);
	void (*showEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QShowEvent* event);
	void (*hideEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QHideEvent* event);
	bool (*nativeEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, struct miqt_string eventType, void* message, long* result);
	int (*metric)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self, int param1);
	void (*initPainter)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self, QPainter* painter);
	QPaintDevice* (*redirected)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self, QPoint* offset);
	QPainter* (*sharedPainter)(struct QsciScintillaBase_VTable* vtbl, const QsciScintillaBase* self);
	void (*timerEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QTimerEvent* event);
	void (*childEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QChildEvent* event);
	void (*customEvent)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QEvent* event);
	void (*connectNotify)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QMetaMethod* signal);
	void (*disconnectNotify)(struct QsciScintillaBase_VTable* vtbl, QsciScintillaBase* self, QMetaMethod* signal);
};
QsciScintillaBase* QsciScintillaBase_new(struct QsciScintillaBase_VTable* vtbl, QWidget* parent);
QsciScintillaBase* QsciScintillaBase_new2(struct QsciScintillaBase_VTable* vtbl);
void QsciScintillaBase_virtbase(QsciScintillaBase* src, QAbstractScrollArea** outptr_QAbstractScrollArea);
QMetaObject* QsciScintillaBase_metaObject(const QsciScintillaBase* self);
void* QsciScintillaBase_metacast(QsciScintillaBase* self, const char* param1);
int QsciScintillaBase_metacall(QsciScintillaBase* self, int param1, int param2, void** param3);
struct miqt_string QsciScintillaBase_tr(const char* s);
struct miqt_string QsciScintillaBase_trUtf8(const char* s);
QsciScintillaBase* QsciScintillaBase_pool();
void QsciScintillaBase_replaceHorizontalScrollBar(QsciScintillaBase* self, QScrollBar* scrollBar);
void QsciScintillaBase_replaceVerticalScrollBar(QsciScintillaBase* self, QScrollBar* scrollBar);
long QsciScintillaBase_SendScintilla(const QsciScintillaBase* self, unsigned int msg);
long QsciScintillaBase_SendScintilla2(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, void* lParam);
long QsciScintillaBase_SendScintilla3(const QsciScintillaBase* self, unsigned int msg, uintptr_t wParam, const char* lParam);
long QsciScintillaBase_SendScintilla4(const QsciScintillaBase* self, unsigned int msg, const char* lParam);
long QsciScintillaBase_SendScintilla5(const QsciScintillaBase* self, unsigned int msg, const char* wParam, const char* lParam);
long QsciScintillaBase_SendScintilla6(const QsciScintillaBase* self, unsigned int msg, long wParam);
long QsciScintillaBase_SendScintilla7(const QsciScintillaBase* self, unsigned int msg, int wParam);
long QsciScintillaBase_SendScintilla8(const QsciScintillaBase* self, unsigned int msg, long cpMin, long cpMax, char* lpstrText);
long QsciScintillaBase_SendScintilla9(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, QColor* col);
long QsciScintillaBase_SendScintilla10(const QsciScintillaBase* self, unsigned int msg, QColor* col);
long QsciScintillaBase_SendScintilla11(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, QPainter* hdc, QRect* rc, long cpMin, long cpMax);
long QsciScintillaBase_SendScintilla12(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, QPixmap* lParam);
long QsciScintillaBase_SendScintilla13(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, QImage* lParam);
void* QsciScintillaBase_SendScintillaPtrResult(const QsciScintillaBase* self, unsigned int msg);
int QsciScintillaBase_commandKey(int qt_key, int* modifiers);
void QsciScintillaBase_QSCN_SELCHANGED(QsciScintillaBase* self, bool yes);
void QsciScintillaBase_connect_QSCN_SELCHANGED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_AUTOCCANCELLED(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_AUTOCCANCELLED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_AUTOCCHARDELETED(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_AUTOCCHARDELETED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_AUTOCCOMPLETED(QsciScintillaBase* self, const char* selection, int position, int ch, int method);
void QsciScintillaBase_connect_SCN_AUTOCCOMPLETED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_AUTOCSELECTION(QsciScintillaBase* self, const char* selection, int position, int ch, int method);
void QsciScintillaBase_connect_SCN_AUTOCSELECTION(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_AUTOCSELECTION2(QsciScintillaBase* self, const char* selection, int position);
void QsciScintillaBase_connect_SCN_AUTOCSELECTION2(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_AUTOCSELECTIONCHANGE(QsciScintillaBase* self, const char* selection, int id, int position);
void QsciScintillaBase_connect_SCN_AUTOCSELECTIONCHANGE(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCEN_CHANGE(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCEN_CHANGE(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_CALLTIPCLICK(QsciScintillaBase* self, int direction);
void QsciScintillaBase_connect_SCN_CALLTIPCLICK(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_CHARADDED(QsciScintillaBase* self, int charadded);
void QsciScintillaBase_connect_SCN_CHARADDED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_DOUBLECLICK(QsciScintillaBase* self, int position, int line, int modifiers);
void QsciScintillaBase_connect_SCN_DOUBLECLICK(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_DWELLEND(QsciScintillaBase* self, int position, int x, int y);
void QsciScintillaBase_connect_SCN_DWELLEND(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_DWELLSTART(QsciScintillaBase* self, int position, int x, int y);
void QsciScintillaBase_connect_SCN_DWELLSTART(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_FOCUSIN(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_FOCUSIN(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_FOCUSOUT(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_FOCUSOUT(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_HOTSPOTCLICK(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_connect_SCN_HOTSPOTCLICK(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_HOTSPOTDOUBLECLICK(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_connect_SCN_HOTSPOTDOUBLECLICK(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_HOTSPOTRELEASECLICK(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_connect_SCN_HOTSPOTRELEASECLICK(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_INDICATORCLICK(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_connect_SCN_INDICATORCLICK(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_INDICATORRELEASE(QsciScintillaBase* self, int position, int modifiers);
void QsciScintillaBase_connect_SCN_INDICATORRELEASE(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_MACRORECORD(QsciScintillaBase* self, unsigned int param1, unsigned long param2, void* param3);
void QsciScintillaBase_connect_SCN_MACRORECORD(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_MARGINCLICK(QsciScintillaBase* self, int position, int modifiers, int margin);
void QsciScintillaBase_connect_SCN_MARGINCLICK(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_MARGINRIGHTCLICK(QsciScintillaBase* self, int position, int modifiers, int margin);
void QsciScintillaBase_connect_SCN_MARGINRIGHTCLICK(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_MODIFIED(QsciScintillaBase* self, int param1, int param2, const char* param3, int param4, int param5, int param6, int param7, int param8, int param9, int param10);
void QsciScintillaBase_connect_SCN_MODIFIED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_MODIFYATTEMPTRO(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_MODIFYATTEMPTRO(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_NEEDSHOWN(QsciScintillaBase* self, int param1, int param2);
void QsciScintillaBase_connect_SCN_NEEDSHOWN(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_PAINTED(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_PAINTED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_SAVEPOINTLEFT(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_SAVEPOINTLEFT(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_SAVEPOINTREACHED(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_SAVEPOINTREACHED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_STYLENEEDED(QsciScintillaBase* self, int position);
void QsciScintillaBase_connect_SCN_STYLENEEDED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_URIDROPPED(QsciScintillaBase* self, QUrl* url);
void QsciScintillaBase_connect_SCN_URIDROPPED(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_UPDATEUI(QsciScintillaBase* self, int updated);
void QsciScintillaBase_connect_SCN_UPDATEUI(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_USERLISTSELECTION(QsciScintillaBase* self, const char* selection, int id, int ch, int method, int position);
void QsciScintillaBase_connect_SCN_USERLISTSELECTION(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_USERLISTSELECTION2(QsciScintillaBase* self, const char* selection, int id, int ch, int method);
void QsciScintillaBase_connect_SCN_USERLISTSELECTION2(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_USERLISTSELECTION3(QsciScintillaBase* self, const char* selection, int id);
void QsciScintillaBase_connect_SCN_USERLISTSELECTION3(QsciScintillaBase* self, intptr_t slot);
void QsciScintillaBase_SCN_ZOOM(QsciScintillaBase* self);
void QsciScintillaBase_connect_SCN_ZOOM(QsciScintillaBase* self, intptr_t slot);
bool QsciScintillaBase_canInsertFromMimeData(const QsciScintillaBase* self, QMimeData* source);
struct miqt_string QsciScintillaBase_fromMimeData(const QsciScintillaBase* self, QMimeData* source, bool* rectangular);
QMimeData* QsciScintillaBase_toMimeData(const QsciScintillaBase* self, struct miqt_string text, bool rectangular);
void QsciScintillaBase_changeEvent(QsciScintillaBase* self, QEvent* e);
void QsciScintillaBase_contextMenuEvent(QsciScintillaBase* self, QContextMenuEvent* e);
void QsciScintillaBase_dragEnterEvent(QsciScintillaBase* self, QDragEnterEvent* e);
void QsciScintillaBase_dragLeaveEvent(QsciScintillaBase* self, QDragLeaveEvent* e);
void QsciScintillaBase_dragMoveEvent(QsciScintillaBase* self, QDragMoveEvent* e);
void QsciScintillaBase_dropEvent(QsciScintillaBase* self, QDropEvent* e);
void QsciScintillaBase_focusInEvent(QsciScintillaBase* self, QFocusEvent* e);
void QsciScintillaBase_focusOutEvent(QsciScintillaBase* self, QFocusEvent* e);
bool QsciScintillaBase_focusNextPrevChild(QsciScintillaBase* self, bool next);
void QsciScintillaBase_keyPressEvent(QsciScintillaBase* self, QKeyEvent* e);
void QsciScintillaBase_inputMethodEvent(QsciScintillaBase* self, QInputMethodEvent* event);
QVariant* QsciScintillaBase_inputMethodQuery(const QsciScintillaBase* self, int query);
void QsciScintillaBase_mouseDoubleClickEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_mouseMoveEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_mousePressEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_mouseReleaseEvent(QsciScintillaBase* self, QMouseEvent* e);
void QsciScintillaBase_paintEvent(QsciScintillaBase* self, QPaintEvent* e);
void QsciScintillaBase_resizeEvent(QsciScintillaBase* self, QResizeEvent* e);
void QsciScintillaBase_scrollContentsBy(QsciScintillaBase* self, int dx, int dy);
struct miqt_string QsciScintillaBase_tr2(const char* s, const char* c);
struct miqt_string QsciScintillaBase_tr3(const char* s, const char* c, int n);
struct miqt_string QsciScintillaBase_trUtf82(const char* s, const char* c);
struct miqt_string QsciScintillaBase_trUtf83(const char* s, const char* c, int n);
long QsciScintillaBase_SendScintilla22(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam);
long QsciScintillaBase_SendScintilla32(const QsciScintillaBase* self, unsigned int msg, unsigned long wParam, long lParam);
QMetaObject* QsciScintillaBase_virtualbase_metaObject(const void* self);
void* QsciScintillaBase_virtualbase_metacast(void* self, const char* param1);
int QsciScintillaBase_virtualbase_metacall(void* self, int param1, int param2, void** param3);
bool QsciScintillaBase_virtualbase_canInsertFromMimeData(const void* self, QMimeData* source);
struct miqt_string QsciScintillaBase_virtualbase_fromMimeData(const void* self, QMimeData* source, bool* rectangular);
QMimeData* QsciScintillaBase_virtualbase_toMimeData(const void* self, struct miqt_string text, bool rectangular);
void QsciScintillaBase_virtualbase_changeEvent(void* self, QEvent* e);
void QsciScintillaBase_virtualbase_contextMenuEvent(void* self, QContextMenuEvent* e);
void QsciScintillaBase_virtualbase_dragEnterEvent(void* self, QDragEnterEvent* e);
void QsciScintillaBase_virtualbase_dragLeaveEvent(void* self, QDragLeaveEvent* e);
void QsciScintillaBase_virtualbase_dragMoveEvent(void* self, QDragMoveEvent* e);
void QsciScintillaBase_virtualbase_dropEvent(void* self, QDropEvent* e);
void QsciScintillaBase_virtualbase_focusInEvent(void* self, QFocusEvent* e);
void QsciScintillaBase_virtualbase_focusOutEvent(void* self, QFocusEvent* e);
bool QsciScintillaBase_virtualbase_focusNextPrevChild(void* self, bool next);
void QsciScintillaBase_virtualbase_keyPressEvent(void* self, QKeyEvent* e);
void QsciScintillaBase_virtualbase_inputMethodEvent(void* self, QInputMethodEvent* event);
QVariant* QsciScintillaBase_virtualbase_inputMethodQuery(const void* self, int query);
void QsciScintillaBase_virtualbase_mouseDoubleClickEvent(void* self, QMouseEvent* e);
void QsciScintillaBase_virtualbase_mouseMoveEvent(void* self, QMouseEvent* e);
void QsciScintillaBase_virtualbase_mousePressEvent(void* self, QMouseEvent* e);
void QsciScintillaBase_virtualbase_mouseReleaseEvent(void* self, QMouseEvent* e);
void QsciScintillaBase_virtualbase_paintEvent(void* self, QPaintEvent* e);
void QsciScintillaBase_virtualbase_resizeEvent(void* self, QResizeEvent* e);
void QsciScintillaBase_virtualbase_scrollContentsBy(void* self, int dx, int dy);
QSize* QsciScintillaBase_virtualbase_minimumSizeHint(const void* self);
QSize* QsciScintillaBase_virtualbase_sizeHint(const void* self);
void QsciScintillaBase_virtualbase_setupViewport(void* self, QWidget* viewport);
bool QsciScintillaBase_virtualbase_eventFilter(void* self, QObject* param1, QEvent* param2);
bool QsciScintillaBase_virtualbase_event(void* self, QEvent* param1);
bool QsciScintillaBase_virtualbase_viewportEvent(void* self, QEvent* param1);
void QsciScintillaBase_virtualbase_wheelEvent(void* self, QWheelEvent* param1);
QSize* QsciScintillaBase_virtualbase_viewportSizeHint(const void* self);
int QsciScintillaBase_virtualbase_devType(const void* self);
void QsciScintillaBase_virtualbase_setVisible(void* self, bool visible);
int QsciScintillaBase_virtualbase_heightForWidth(const void* self, int param1);
bool QsciScintillaBase_virtualbase_hasHeightForWidth(const void* self);
QPaintEngine* QsciScintillaBase_virtualbase_paintEngine(const void* self);
void QsciScintillaBase_virtualbase_keyReleaseEvent(void* self, QKeyEvent* event);
void QsciScintillaBase_virtualbase_enterEvent(void* self, QEvent* event);
void QsciScintillaBase_virtualbase_leaveEvent(void* self, QEvent* event);
void QsciScintillaBase_virtualbase_moveEvent(void* self, QMoveEvent* event);
void QsciScintillaBase_virtualbase_closeEvent(void* self, QCloseEvent* event);
void QsciScintillaBase_virtualbase_tabletEvent(void* self, QTabletEvent* event);
void QsciScintillaBase_virtualbase_actionEvent(void* self, QActionEvent* event);
void QsciScintillaBase_virtualbase_showEvent(void* self, QShowEvent* event);
void QsciScintillaBase_virtualbase_hideEvent(void* self, QHideEvent* event);
bool QsciScintillaBase_virtualbase_nativeEvent(void* self, struct miqt_string eventType, void* message, long* result);
int QsciScintillaBase_virtualbase_metric(const void* self, int param1);
void QsciScintillaBase_virtualbase_initPainter(const void* self, QPainter* painter);
QPaintDevice* QsciScintillaBase_virtualbase_redirected(const void* self, QPoint* offset);
QPainter* QsciScintillaBase_virtualbase_sharedPainter(const void* self);
void QsciScintillaBase_virtualbase_timerEvent(void* self, QTimerEvent* event);
void QsciScintillaBase_virtualbase_childEvent(void* self, QChildEvent* event);
void QsciScintillaBase_virtualbase_customEvent(void* self, QEvent* event);
void QsciScintillaBase_virtualbase_connectNotify(void* self, QMetaMethod* signal);
void QsciScintillaBase_virtualbase_disconnectNotify(void* self, QMetaMethod* signal);
const QMetaObject* QsciScintillaBase_staticMetaObject();
void QsciScintillaBase_delete(QsciScintillaBase* self);

#ifdef __cplusplus
} /* extern C */
#endif

#endif
